### ISSUE TITLE
Wallpaper changing not implemented on some Linux DEs

### ISSUE THREAD

**Issue by vinyldarkscratch** [GooborgStudios/synglechance#18]
The wallpaper changing is not implemented for some Linux desktop environments.  Planned DEs to implement for are the following:

- [x] GNOME
- [x] Cinnamon
- [x] MATE
- [x] Xfce
- [x] KDE
- [x] Deepin
- [ ] LXDE

(More to possibly come for those that request it!)

**Comment by vinyldarkscratch** [comment]
This is being resolved in the `linux` branch, special thanks to @KockaAdmiralac for the wonderful work on it!

**Comment by Yummychickenblue** [comment]
@KockaAdmiralac Is there any plan for an implementation of this functionality in KDE Plasma/Kwin? It looks like there is code for GNOME right now in `wallpaper-binding.cpp`

**Comment by KockaAdmiralac** [comment]
I just yesterday started installing KDE on a VM to test that :P

**Comment by KockaAdmiralac** [comment]
The wallpaper changing should be implemented on Xfce now. I'll look into implementing it on KDE later, since I had some issues last time I tried.

**Comment by KockaAdmiralac** [comment]
MATE support is also done now!

**Comment by vinyldarkscratch** [comment]
I'm now working on the Linux port as well.  Testing it out on Linux Mint with Cinnamon, it seems that when it's resetting the background, it's only resetting to the default.  So, seems like something's acting up.  Will be fixing it soon!

**Comment by vinyldarkscratch** [comment]
Implementing on KDE looks like it's gonna be a bit of a pain.  I'm adding the "help wanted" tag onto this issue in response.

**Comment by vinyldarkscratch** [comment]
For LXDE, I found this [StackOverflow](https://askubuntu.com/questions/309695/wallpaper-refresh) question that appears to be quite helpful, and a step in the right direction.  I'll get to implementing this ASAP.

**Comment by Yummychickenblue** [comment]
@vinyldarkscratch 
> Implementing on KDE looks like it's gonna be a bit of a pain. I'm adding the "help wanted" tag onto this >issue in response.

What issues are you having specifically with Plasma? I found a dbus command that allows one to script changing the background 

`qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file:///home/cubby/Pictures/bluewagon")}'`

I've tested this on Plasma 5.12, the latest LTS as of the time of this post.

**Comment by vinyldarkscratch** [comment]
@Yummychickenblue There's more to it than just that.  We'll also need to obtain the current desktop background the user has, so we can change it back after we've completed execution.

**Comment by Yummychickenblue** [comment]
@vinyldarkscratch  it can be read from `~/.config/plasma-org.kde.plasma.desktop-appletsrc`

**Comment by KockaAdmiralac** [comment]
I have implemented support for changing (and resetting) the wallpaper on KDE now and pushed it to the `linux` branch. As far as I've tested, it should work, but as the whole `system()` call using JavaScript inside Bash inside C++ can be very unstable it would require some further testing.

**Comment by KockaAdmiralac** [comment]
We've got the most used desktop environments covered for the first Linux release, and a fallback for unsupported desktop environments has been implemented. For DE support requests please open new issues.
