### ISSUE TITLE
Journal icon on Linux isn't a clover

### ISSUE THREAD

**Issue by KockaAdmiralac** [GooborgStudios/synglechance#26]
We need to make sure `~/Documents/Oneshot/_______` has a proper clover icon:
![Image](https://i.imgur.com/6AxoJ3Q.png)
Currently, it's just a symlink. If symlinks won't take proper icons of their respective programs we might want to consider making a `.desktop` file for it.

**Comment by Yummychickenblue** [comment]
Have you tested with multiple file managers?

**Comment by vinyldarkscratch** [comment]
I can confirm this is actually an issue, yes -- the clover icon isn't even being added in through PyInstaller, and on macOS is added via a little script.

**Comment by vinyldarkscratch** [comment]
Should be fixed in 96ca228d499dbe4514d302d2ac80f520673c8ff4!  I have no way of testing to double-check, however... >~<

**Comment by vinyldarkscratch** [comment]
I just got the ability to check up on this.  Looks like the commit didn't actually fix the issue.  Creating a `.desktop` file doesn't sound like a bad option, yeah.  I'll be happy to help with the Linux side of things again, now that the macOS port is finished.  :)

**Comment by KockaAdmiralac** [comment]
This seems to be mostly fixed in the `linux` branch now. I tested it on Linux Mint, Ubuntu, Xfce, KDE and MATE and it seems that only Ubuntu (18.04) doesn't want to show the Journal's icon as a clover because the .desktop file has not been marked as trusted (even though it has been marked as executable). As this seems to be a restriction of Ubuntu and nothing that we can really fix, I don't think there would be any way to get the icon to show in the folder.

@vinyldarkscratch what do you think?

**Comment by KockaAdmiralac** [comment]
It seems that in Ubuntu 18.10 the icon is showing up after marking the launcher as trusted. As there isn't anything we can really do to fix this, I'm closing this issue.
