### ISSUE TITLE
Segmentation fault when moving window before GTK libraries loaded

### ISSUE THREAD

**Issue by KockaAdmiralac** [GooborgStudios/synglechance#28]
The issue happens on [eventthread.cpp:595](https://github.com/GooborgStudios/synglechance/blob/master/src/eventthread.cpp#L595) according to gdb because `shState->oneshot()` isn't defined(?)

@vinyldarkscratch why are we linking GTK libraries dynamically? I believe OneShot loads very slowly and leads to this issue when the window is moved because of that.

**Comment by vinyldarkscratch** [comment]
Closing this issue because you were talking about this in the Discord chat, and simply stopped dynamically linking the GTK libraries, which fixed some other issues as well.  :P
