### ISSUE TITLE
Crash when ~/Documents/Oneshot/_______.app already exists

### ISSUE THREAD

**Issue by pokedart9001** [GooborgStudios/synglechance#33]
![screen shot 2018-04-22 at 10 03 37 pm](https://user-images.githubusercontent.com/12713120/39103566-859ba5a8-4679-11e8-9492-dc6eeb06fc1c.png)
This error happened while I was testing this part of the game to see if version 0.8.1 fixed the issues mentioned in issue #29. I'm not sure if `_______.app` gets deleted from `~/Documents/Oneshot` automatically during a normal playthrough, but if it doesn't, then it's possible that this issue might occur if someone is replaying the game and hasn't deleted `_______.app`.

**Comment by vinyldarkscratch** [comment]
Hmm, that's weird, I thought I set it to overwrite the file just in case...  99% of the time, this won't be an issue as the file will never exist until after the creation, but might as well have a failsafe in case OneShot crashes after the file's been created.  😛
