### ISSUE TITLE
No save_unix.png in Tower on macOS

### ISSUE THREAD

**Issue by pokedart9001** [GooborgStudios/synglechance#34]
![save_unix](https://user-images.githubusercontent.com/12713120/39104040-65e4429e-467c-11e8-8325-46e66bbe3850.png)
I know @KockaAdmiralac said something in issue #29 about how this issue was fixed in the `linux` branch, and `save.png` did appear correctly when opening `_______.app` after the credits, but `save_unix.png` still didn't appear after the game closed.

**Comment by vinyldarkscratch** [comment]
I've never actually seen this image in my playthrough of the game...but then now that I think about it, I played this part on macOS anyways.  XD  I'll have to play through the game to figure out when it appears on Windows, and then work from there!

**Comment by pokedart9001** [comment]
If that's the case, then that means the story should only continue as normal once the journal is running alongside OneShot. I figured as much since I've seen comments on the Steam forums saying that when they open the game Niko is still sleeping and they don't know what to do next.

**Comment by vinyldarkscratch** [comment]
Hey @pokedart9001, I've been having issues with #35 that have been preventing me from even getting to this part.  Once Niko goes to sleep, does it go straight to the dream before you open the journal, or do you have to open the journal?
