### ISSUE TITLE
Basement door fade-in/fade-out effect plays twice

### ISSUE THREAD

**Issue by markdegica** [GooborgStudios/synglechance#36]
When entering/exiting the basement in the house, the screen fade-in/out plays twice: once when you enter the door, and then again after the transition is already complete. The door opening sfx plays in the first transition, and the door closing sfx plays in the second.
<img width="1280" alt="screen shot 2018-04-27 at 12 20 03 pm" src="https://user-images.githubusercontent.com/38886447/39480048-0d52c7c6-4d35-11e8-8304-c566f43eb880.png">

**Comment by vinyldarkscratch** [comment]
Just confirmed this is actually happening on my end, though not sure why...

**Comment by vinyldarkscratch** [comment]
Fixed it -- looks like the teleport's "Fading" was conflicting with our own programmed fading effects.  I turned them off in the RPG Maker files.  ;)
