### ISSUE TITLE
Game forces fullscreen instead of window in the tower

### ISSUE THREAD

**Issue by markdegica** [GooborgStudios/synglechance#37]
When relaunching the game in the Tower after Niko goes into the bed (without the journal open), the game forces full-screen. It should be in Window mode since the wallpaper changes to reveal the hint. If you switch back to window and close the game, it will still force fullscreen every time.

Also after switching between fullscreen and window and closing the game the wallpaper didn't change back like it normally does.

**Comment by vinyldarkscratch** [comment]
The part about the wallpaper is somewhat tied into #13.  I was hoping that it wouldn't be noticed, but I guess it's an issue...  Essentially, with macOS fullscreen, it treats the fullscreen app like it's own desktop.  I thought that it wouldn't be a big enough deal to mention, but from what you're saying, it is.

For the fullscreen forcing, I think that the game might be getting confused on whether it's in fullscreen or not.  These are a few of the issues I'm hoping to have worked out ASAP!

**Comment by vinyldarkscratch** [comment]
Doing a little research, I just tried this out on Windows to see if this is a thing.  Turns out, this is.  So, this is an issue upstream as well.  >~<

**Comment by vinyldarkscratch** [comment]
Figured out a way to solve this issue.  When (re)setting the wallpaper, just have the game hop out of fullscreen.  It also makes the wallpaper easier to see.  😛
