### ISSUE TITLE
Popup boxes forcing user out of fullscreen creates "ghost" window

### ISSUE THREAD

**Issue by markdegica** [GooborgStudios/synglechance#38]
If the game is fullscreen when entering the door that leads to the first maze in the Tower, it will open up another game window with the title OneShot. This window cannot be interacted with. It will not disappear until the app is closed.

<img width="1280" alt="screen shot 2018-04-30 at 2 22 21 pm" src="https://user-images.githubusercontent.com/38886447/39480911-b20b62da-4d37-11e8-80cc-cb3e8118cb06.png">

**Comment by vinyldarkscratch** [comment]
Just found this bug...this is a strange one for sure.  It'll be fun to dig into for sure!

**Comment by vinyldarkscratch** [comment]
While trying to solve #37, I noticed something interesting: I got that same second window issue when fullscreen was forced off when I tried to quit, and got a dialogue popup.  I'm able to consistently replicate this issue by going fullscreen and getting dialogue popups to appear.

**Comment by vinyldarkscratch** [comment]
Thanks to @KockaAdmiralac for confirming this is a macOS-only issue!

**Comment by vinyldarkscratch** [comment]
I see what's going on: during the transition between fullscreen and windowed, SDL doesn't recognize the fact that we already have a window, and tries to create a new one so it can show a dialogue.  We just need to increase the sleep time on macOS.  :P
