### ISSUE TITLE
Journal does not update if closed and re-opened

### ISSUE THREAD

**Issue by markdegica** [GooborgStudios/synglechance#39]
If you close the journal window and re-open it, it will no longer update, even when transitioning between screens. Without the journal hints, the player will be forced to restart the section.

<img width="1280" alt="screen shot 2018-04-30 at 2 26 11 pm" src="https://user-images.githubusercontent.com/38886447/39481010-fbe81718-4d37-11e8-80f9-340149d1e0cf.png">

**Comment by vinyldarkscratch** [comment]
Didn't think that this would be an issue, but I guess it is.  I'll take a look into it and see if I can get it fixed ASAP.  ;)

**Comment by popkirby** [comment]
https://github.com/GooborgStudios/synglechance/blob/d9357ef4f360d493b0ee102d9baee46402635154/journal/unix/journal.py#L204-L207

Journal app is unlinking pipe, while OneShot is opening it and continues writing.
I fixed this problem and will submit pull request.

However, the hint image corresponding to the scene will not be loaded right after re-opening Journal app, maybe we should disable closing Journal button in the hint images mode.

**Comment by vinyldarkscratch** [comment]
Hold up, @popkirby.  There's a reason why the pipe file is removed by the journal.  The existence of the pipe file is how OneShot determines that the journal is currently open.  If we have OneShot create and delete the pipe, then it will assume that the journal is open.

**Comment by popkirby** [comment]
I think the `active` variable is only set to true when Journal app opens because OneShot's `out_pipe = open(PIPE_PATH, O_WRONLY | ...)` blocks until Journal apps's `os.open(pipe_path, os.O_RDONLY | os.O_NONBLOCK)` and `journal = true` exists after the `out_pipe` assignment.

**Comment by vinyldarkscratch** [comment]
Just pushed the changes that'll fix this issue now!
