### ISSUE TITLE
Latest release zip (1.0.2) doesn't contain xScripts.rxdata

### ISSUE THREAD

**Issue by benvan** [GooborgStudios/synglechance#46]

**Comment by vinyldarkscratch** [comment]
H-heheh, oops...  Fixed now!  (I updated the same release to include the file, I know that I should bump the version number if I make changes, but I'm lazy.  :P)  The release file now contains the xScripts.rxdata file.  ;)

**Comment by benvan** [comment]
Thanks! :)
