### ISSUE TITLE
pt-br translation issue in save_unix.png

### ISSUE THREAD

**Issue by KockaAdmiralac** [GooborgStudios/synglechance#47]
@ryu-ketsueki (Ryū Ketsueki#1192) noticed an issue in the pt-br translation:
![Image](https://cdn.discordapp.com/attachments/445718933312634891/445986271505022976/unknown.png)
It should be *história*, not *hisória*. This is somehow specific to SyngleChance, since the same image (`save_w32.bmp`) in OneShot looks like this:
![Image](https://i.imgur.com/SJ73sDP.png)

**Comment by vinyldarkscratch** [comment]
Oops, that'd be a typo on my end, that's my bad.  Will have this fixed ASAP!
