### ISSUE TITLE
_______.app won't run on <= 10.12

### ISSUE THREAD

**Issue by vinyldarkscratch** [GooborgStudios/synglechance#49]
Some users are having problems opening the journal application on macOS.
https://steamcommunity.com/app/420530/discussions/1/1698300679760832499/
https://steamcommunity.com/app/420530/discussions/1/1698300679764416690/

**Comment by vinyldarkscratch** [comment]
This appears to be affecting many users on many different versions of macOS.  Looks like the clover app wasn’t generated properly.

**Comment by popkirby** [comment]
At least, `futimens` is introduced in macOS High Sierra, so the application will not run on <= 10.12. I reintroduced this problem on 10.12.6. (same error as https://steamcommunity.com/app/420530/discussions/1/1698300679760832499/#c1698300679768115477)

However, I have not been able to reproduce on High Sierra.

**Comment by vinyldarkscratch** [comment]
Hey thanks @popkirby!  Yeah, I thought it might have something to do with Sierra, but someone said they had the error on High Sierra as well.  Looks like it's going to be a relatively easy fix...  Whew!

**Comment by skybrian** [comment]
Hi, I'm still getting the "_futimens" error with 10.12.6. I guess the update isn't on Steam yet?

**Comment by vinyldarkscratch** [comment]
Hey @skybrian, I sent Degica the patch, but it doesn't like they've updated it.  I'm going to be adding El Capitan support as well as ensure functionality on Sierra right now.  😉

**Comment by vinyldarkscratch** [comment]
Unfortunately Degica has confirmed that this is still an issue.

**Comment by vinyldarkscratch** [comment]
Notes for myself:

- `futimens` call coming from Python, which should be built for 10.10 but is built for 10.13.

**Comment by vinyldarkscratch** [comment]
This is now fixed by using the Python version supplied by Python.org.  Will be applied next patch.
